name: Android CI

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up dependecies
      uses: actions/setup-java@v1
      uses: actions/setup-python@v1
      with:
        java-version: 1.8
        python-version: 3.7.5
    - name: Create Key Files
      run: python3 gh-actions-post-clone.py  ${{ secrets.hockey_app_secret }} ${{ secrets.firebase_dev_json }} ${{ secrets.firebase_prod_json }}
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
